Repository kodlamaio-projects/nArchitecture.RentACarProject, pull requests merged in 2022-10, with the labels that each got.

#30 feat(core.mailing): cc and bcc list added, authentication activated
  src/corePackages/Core.Mailing/Mail.cs
  src/corePackages/Core.Mailing/MailKitImplementations/MailKitMailService.cs
  src/corePackages/Core.Mailing/MailSettings.cs
  src/rentACar/WebAPI/appsettings.json
Labels: needs enhancements

#33 refactor(Application/ApplicationServiceRegistration): Add the BaseBusinessRules and AddSubClassesOfType method
  src/corePackages/Core.Application/Rules/BaseBusinessRules.cs
  src/rentACar/Application/ApplicationServiceRegistration.cs
  src/rentACar/Application/Features/AdditionalServices/Rules/AdditionalServiceBusinessRules.cs
  src/rentACar/Application/Features/Auths/Rules/AuthBusinessRules.cs
  src/rentACar/Application/Features/Brands/Rules/BrandBusinessRules.cs
  src/rentACar/Application/Features/CarDamages/Rules/CarDamageBusinessRules.cs
  src/rentACar/Application/Features/Cars/Rules/CarBusinessRules.cs
  src/rentACar/Application/Features/Colors/Rules/ColorBusinessRules.cs
  src/rentACar/Application/Features/CorporateCustomers/Rules/CorporateCustomerBusinessRules.cs
  src/rentACar/Application/Features/Customers/Rules/CustomerBusinessRules.cs
  src/rentACar/Application/Features/FindeksCreditRates/Rules/FindeksCreditRateBusinessRules.cs
  src/rentACar/Application/Features/Fuels/Rules/FuelBusinessRules.cs
  src/rentACar/Application/Features/IndividualCustomers/Rules/IndividualCustomerBusinessRules.cs
  src/rentACar/Application/Features/Invoices/Rules/InvoiceBusinessRules.cs
  src/rentACar/Application/Features/Models/Rules/ModelBusinessRules.cs
  src/rentACar/Application/Features/OperationClaims/Rules/OperationClaimBusinessRules.cs
  src/rentACar/Application/Features/RentalBranches/Rules/RentalBranchBusinessRules.cs
  src/rentACar/Application/Features/Rentals/Rules/RentalBusinessRules.cs
  src/rentACar/Application/Features/Transmissions/Rules/TransmissionBusinessRules.cs
  src/rentACar/Application/Features/UserOperationClaims/Rules/UserOperationClaimBusinessRules.cs
  src/rentACar/Application/Features/Users/Rules/UserBusinessRules.cs
Labels: needs refactor

#36 feat(Core.Persistence) Add Null and symbol control in Dynamic Query Ex…
  src/corePackages/Core.Persistence/Dynamic/IQueryableDynamicFilterExtensions.cs
Labels: needs review

#58 refactor(Core.CrossCuttingConcerns): Refactor Global-Exception-Handling
  src/corePackages/Core.CrossCuttingConcers/Exceptions/AuthorizationProblemDetails.cs
  src/corePackages/Core.CrossCuttingConcers/Exceptions/BusinessProblemDetails.cs
  src/corePackages/Core.CrossCuttingConcers/Exceptions/ExceptionMiddleware.cs
  src/corePackages/Core.CrossCuttingConcers/Exceptions/Handlers/ExceptionHandler.cs
  src/corePackages/Core.CrossCuttingConcers/Exceptions/Handlers/HttpExceptionHandler.cs
  src/corePackages/Core.CrossCuttingConcers/Exceptions/HttpProblemDetails/AuthorizationProblemDetails.cs
  src/corePackages/Core.CrossCuttingConcers/Exceptions/HttpProblemDetails/BusinessProblemDetails.cs
  src/corePackages/Core.CrossCuttingConcers/Exceptions/HttpProblemDetails/InternalServerErrorProblemDetails.cs
  src/corePackages/Core.CrossCuttingConcers/Exceptions/HttpProblemDetails/NotFoundProblemDetails.cs
  src/corePackages/Core.CrossCuttingConcers/Exceptions/HttpProblemDetails/ProblemDetailsExtensions.cs
  src/corePackages/Core.CrossCuttingConcers/Exceptions/HttpProblemDetails/ValidationProblemDetails.cs
  src/corePackages/Core.CrossCuttingConcers/Exceptions/NotFoundException.cs
  src/corePackages/Core.CrossCuttingConcers/Exceptions/NotFoundProblemDetails.cs
  src/corePackages/Core.CrossCuttingConcers/Exceptions/ValidationProblemDetails.cs
Labels: needs enhancements

#61 feat(application): add validators
  src/rentACar/Application/Features/AdditionalServices/Commands/CreateAdditionalService/CreateAdditionalServiceCommandValidator.cs
  src/rentACar/Application/Features/AdditionalServices/Commands/UpdateAdditionalService/UpdateAdditionalServiceCommandValidator.cs
  src/rentACar/Application/Features/Brands/Commands/UpdateBrand/UpdateBrandCommandValidator.cs
  src/rentACar/Application/Features/CarDamages/Commands/CreateCarDamage/CreateCarDamageCommandValidator.cs
  src/rentACar/Application/Features/CarDamages/Commands/UpdateCarDamage/UpdateCarDamageCommandValidator.cs
  src/rentACar/Application/Features/Colors/Commands/CreateColor/CreateColorCommandValidator.cs
  src/rentACar/Application/Features/Colors/Commands/UpdateColor/UpdateColorCommandValidator.cs
  src/rentACar/Application/Features/CorporateCustomers/Commands/CreateCorporateCustomer/CreateCorporateCustomerCommandValidator.cs
  src/rentACar/Application/Features/CorporateCustomers/Commands/UpdateCorporateCustomer/UpdateCorporateCustomerCommandValidator.cs
  src/rentACar/Application/Features/Customers/Commands/CreateCustomer/CreateCustomerCommandValidator.cs
  src/rentACar/Application/Features/Customers/Commands/UpdateCustomer/UpdateCustomerCommandValidator.cs
  src/rentACar/Application/Features/FindeksCreditRates/Commands/UpdateByUserIdFindeksCreditRateFromService/UpdateByUserIdFindeksCreditRateFromServiceCommandValidator.cs
  src/rentACar/Application/Features/FindeksCreditRates/Commands/UpdateFindeksCreditRateFromService/UpdateFindeksCreditRateFromServiceCommandValidator.cs
  src/rentACar/Application/Features/Fuels/Commands/CreateFuel/CreateFuelCommandValidator.cs
  src/rentACar/Application/Features/Fuels/Commands/UpdateFuel/UpdateFuelCommandValidator.cs
  src/rentACar/Application/Features/IndividualCustomers/Commands/CreateIndividualCustomer/CreateIndividualCustomerCommandValidator.cs
  src/rentACar/Application/Features/IndividualCustomers/Commands/UpdateIndividualCustomer/UpdateIndividualCustomerCommandValidator.cs
  src/rentACar/Application/Features/Invoices/Commands/CreateInvoice/CreateInvoiceCommandValidator.cs
  src/rentACar/Application/Features/Invoices/Commands/UpdateInvoice/UpdateInvoiceCommandValidator.cs
  src/rentACar/Application/Features/Models/Commands/UpdateModel/UpdateModelCommandValidator.cs
  src/rentACar/Application/Features/OperationClaims/Commands/CreateOperationClaim/CreateOperationClaimCommandValidator.cs
  src/rentACar/Application/Features/OperationClaims/Commands/UpdateOperationClaim/UpdateOperationClaimCommandValidator.cs
  src/rentACar/Application/Features/RentalBranches/Commands/CreateRentalBranch/CreateRentalBranchCommandValidator.cs
  src/rentACar/Application/Features/RentalBranches/Commands/UpdateRentalBranch/UpdateRentalBranchCommandValidator.cs
  src/rentACar/Application/Features/Rentals/Commands/PickUpRental/PickUpRentalCommandValidator.cs
  src/rentACar/Application/Features/Transmissions/Commands/CreateTransmission/CreateTransmissionCommandValidator.cs
  src/rentACar/Application/Features/Transmissions/Commands/UpdateTransmission/UpdateTransmissionCommandValidator.cs
  src/rentACar/Application/Features/UserOperationClaims/Commands/CreateUserOperationClaim/CreateUserOperationClaimCommandValidator.cs
  src/rentACar/Application/Features/UserOperationClaims/Commands/UpdateUserOperationClaim/UpdateUserOperationClaimCommandValidator.cs
  src/rentACar/Application/Features/Users/Commands/CreateUser/CreateUserCommandValidator.cs
  src/rentACar/Application/Features/Users/Commands/UpdateUser/UpdateUserCommandValidator.cs
  src/rentACar/Application/Features/Users/Commands/UpdateUserFromAuth/UpdateUserFromAuthCommandValidator.cs
Labels: needs enhancements
